# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: "{{ region }}/{{ city }}"

- name: Set new hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ packages }}"
  become: true

- name: Manage swap file
  block:
    - name: Create a swap file
      ansible.builtin.shell: fallocate -l {{ swap_size }} "{{ swapfile }}"
      args:
        creates: "{{ swapfile }}"

    - name: Set the correct permissions
      ansible.builtin.file:
        path: "{{ swapfile }}"
        owner: root
        group: root
        mode: '0600'

    - name: Make the file a swap file
      ansible.builtin.shell: mkswap "{{ swapfile }}"
      when: ansible_facts.swapfree_mb == 0

    - name: Enable the swap file
      ansible.builtin.shell: swapon "{{ swapfile }}"
      when: ansible_facts.swapfree_mb == 0

    - name: Add swap file to fstab
      ansible.posix.mount:
        name: none
        src: "{{ swapfile }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
