# SPDX-License-Identifier: MIT-0
---
# tasks file for swaptrasher
- name: Swap disable
  block:
  - name: Check swap
    ansible.builtin.shell: swapon --show
    register: swap_status
    changed_when: false
    failed_when: false

  - name: Disable swap 
    ansible.builtin.shell: swapoff -a
    when: disable_swap and swap_status.stdout != ""

  - name: Remove swapfile
    ansible.builtin.file:
      path: "{{ swapfile }}"
      state: absent
    when: disable_swap and swap_status.stdout != ""

  - name: Remove swap entry from /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: '^.*{{ swapfile }}.*$'
      state: absent
    when: disable_swap and swap_status.stdout != ""
